Cargando sesión...
Explicar
Console Error

Hydration failed because the server rendered HTML didn't match the client. As a result this tree will be regenerated on the client. This can happen if a SSR-ed Client Component used:

- A server/client branch `if (typeof window !== 'undefined')`.
- Variable input such as `Date.now()` or `Math.random()` which changes each time it's called.
- Date formatting in a user's locale which doesn't match the server.
- External changing data without sending a snapshot of it along with the HTML.
- Invalid HTML tag nesting.

It can also happen if the client has a browser extension installed which messes with the HTML before React loaded.

See more info here: https://nextjs.org/docs/messages/react-hydration-error

  ...
    <HotReload assetPrefix="" globalError={[...]}>
      <AppDevOverlay state={{nextId:1, ...}} globalError={[...]}>
        <AppDevOverlayErrorBoundary globalError={[...]} onError={function bound dispatchSetState}>
          <ReplaySsrOnlyErrors>
          <DevRootHTTPAccessFallbackBoundary>
            <HTTPAccessFallbackBoundary notFound={<NotAllowedRootHTTPFallbackError>}>
              <HTTPAccessFallbackErrorBoundary pathname="/" notFound={<NotAllowedRootHTTPFallbackError>} ...>
                <RedirectBoundary>
                  <RedirectErrorBoundary router={{...}}>
                    <Head>
                    <link>
                    <script>
                    <script>
                    <script>
                    <script>
                    <RootLayout>
                      <html lang="es" suppressHydrationWarning={true} className="dark">
                        <head>
                        <body
                          className="geist_e531dabc-module__QGiZLq__variable geist_mono_68a01160-module__YLcDdW__varia..."
-                         monica-id="ofpnmcalabcbjgholdjcjblkibolbppb"
-                         monica-version="7.9.3"
                        >
                    ...
        ...
src/app/layout.tsx (43:7) @ RootLayout

  41 |         />
  42 |       </head>
> 43 |       <body className={`${geistSans.variable} ${geistMono.variable} antialiased bg-background text-foreground`}>
     |       ^
  44 |         <AuthProvider>
  45 |           {children}
  46 |           <Toaster />
Call Stack
17

Hide 15 ignore-listed frame(s)
createUnhandledError
node_modules/next/src/client/components/errors/console-error.ts (18:35)
handleClientError
node_modules/next/src/client/components/errors/use-error-handler.ts (31:33)
console.error
node_modules/next/src/client/components/globals/intercept-console-error.ts (32:26)
<unknown>
node_modules/next/dist/compiled/react-dom/cjs/react-dom-client.development.js (13501:19)
runWithFiberInDEV
node_modules/next/dist/compiled/react-dom/cjs/react-dom-client.development.js (1510:30)
emitPendingHydrationWarnings
node_modules/next/dist/compiled/react-dom/cjs/react-dom-client.development.js (13500:9)
completeWork
node_modules/next/dist/compiled/react-dom/cjs/react-dom-client.development.js (13661:18)
runWithFiberInDEV
node_modules/next/dist/compiled/react-dom/cjs/react-dom-client.development.js (1513:13)
completeUnitOfWork
node_modules/next/dist/compiled/react-dom/cjs/react-dom-client.development.js (15255:19)
performUnitOfWork
node_modules/next/dist/compiled/react-dom/cjs/react-dom-client.development.js (15136:11)
workLoopConcurrentByScheduler
node_modules/next/dist/compiled/react-dom/cjs/react-dom-client.development.js (15113:9)
renderRootConcurrent
node_modules/next/dist/compiled/react-dom/cjs/react-dom-client.development.js (15088:15)
performWorkOnRoot
node_modules/next/dist/compiled/react-dom/cjs/react-dom-client.development.js (14409:13)
performWorkOnRootViaSchedulerTask
node_modules/next/dist/compiled/react-dom/cjs/react-dom-client.development.js (16274:7)
MessagePort.performWorkUntilDeadline
node_modules/next/dist/compiled/scheduler/cjs/scheduler.development.js (45:48)
body
<anonymous> (0:0)
RootLayout
src/app/layout.tsx (43:7) Cargando sesión...

Explicar
Console Error

Error: Detected container element removed from DOM

src/app/page.tsx (157:57) @ PayPalSmartPaymentButtons.useEffect

  155 |
  156 |         if (paypalButtonsContainerRef.current) {
> 157 |              paypalButtonsContainerRef.current.innerHTML = '';
      |                                                         ^
  158 |              buttonsInstance.render(paypalButtonsContainerRef.current)
  159 |             .then(() => {
  160 |                 setPayPalButtonInstance(buttonsInstance);
Call Stack
4

Hide 3 ignore-listed frame(s)
<unknown>
https://www.paypal.com/sdk/js (3:110003)
<unknown>
https://www.paypal.com/sdk/js (3:29245)
l
https://www.paypal.com/sdk/js (3:109525)
PayPalSmartPaymentButtons.useEffect
src/app/page.tsx (157:57)